In [48]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import make_regression
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder, StandardScaler
from numpy import array
import numpy
import pandas

data = pandas.read_json('./data.json')
#data = data.head()
data = data.drop(['filename'],axis=1)
data = data.head(450)
genre_list = data.iloc[:, 0]
    
encoder = LabelEncoder()
yGenres = encoder.fit_transform(genre_list)
# Angry, Happy, Relaxed, Sad
XTracks = numpy.array(data.iloc[:, 1:], dtype = float)    

# generate regression dataset

X = XTracks
y = yGenres

scalarX, scalarY = MinMaxScaler(), MinMaxScaler()
scalarX.fit(X)

scaler = StandardScaler()

print(scaler.fit_transform(X))
print(scalarX.fit_transform(X))
X = scalarX.fit_transform(X)

# define and fit the final model
model = Sequential()
model.add(Dense(4, input_shape=(X.shape[1],), activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(1, activation='linear'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mse', optimizer='adam')
model.fit(X, y, epochs=30, verbose=False)
# new instance where we do not know the answer
Xnew = array([X[400]])
# make a prediction
ynew = model.predict(Xnew)
# show the inputs and predicted outputs
print("X=%s, Predicted=%s, Result=%s" % (Xnew[0], ynew[0], numpy.argmax(ynew[0])))


[[ 1.97078811 -0.00264214 -1.0737126  ... -1.89049045  1.5545892
  -1.25619467]
 [ 1.55071627 -0.42694779 -0.11007222 ...  0.59785822 -0.31616325
   0.65990093]
 [-0.18485484  0.27231828  0.35436629 ...  1.0890116   0.28842696
   0.82123245]
 ...
 [-0.72779563 -0.71908644 -0.63014565 ... -1.24158907  1.76018221
  -1.11988922]
 [-0.43478339 -0.35727698  0.28567164 ...  0.34345381 -0.4935394
   0.17078686]
 [ 0.43619322  0.30413935  1.03472585 ...  0.97761511 -0.22023614
   1.23341565]]
[[0.87699199 0.47783551 0.4115961  ... 0.16236142 0.80289728 0.30833927]
 [0.79777424 0.40884202 0.58697717 ... 0.6403869  0.47834692 0.65782604]
 [0.47047776 0.52254498 0.67150426 ... 0.73474017 0.58323518 0.68725215]
 ...
 [0.3680892  0.36133932 0.4923246  ... 0.28701895 0.8385649  0.33320074]
 [0.42334587 0.42017073 0.65900194 ... 0.59151441 0.44757455 0.56861395]
 [0.58759589 0.52771919 0.79532865 ... 0.71334029 0.49498899 0.76243241]]
X=[0.32811958 0.3684572  0.56596659 0.41829308 0.22253212 0.634858